In [1]:
import numpy as np
import pandas as pd

# Simulations == Monte Carlo Method
- Simulation is running an experiment
- Trial is the number of items in each experiment

## How to run a simulation with Python/Numpy/Pandas
1. Figure out a way to represent our data
2. Create a matrix of random data, rows = simulations, columns = trial
    - For example, rolling 2 dice 10,000 times means rows=10,000 and columns = 2 because we roll 2 dice each time.
3. Apply an aggregate function, row-wise to get the results of the simulation
4. Apply a final aggregate to get our probability

In [2]:
# Let's answer questions experimentally rather than theoretically
# What's the probability of flipping "Heads" on a coin?

# Let's flip a coin 100,000 times and figure out the probability of flipping "Heads"

# Let's find a way to represent out data
outcomes = ["Heads", "Tails"] # list of strings
n_simulations = 1_000_000

flips = np.random.choice(outcomes,  size=n_simulations)# from an array like pandas series, numpy; size is the how
                                                        # many times to run the simulations
flips[0:5] # python has no .head() so this is how we show first five

array(['Tails', 'Tails', 'Tails', 'Tails', 'Heads'], dtype='<U5')

In [3]:
# After flipping one million coins, our experiemental probability of flipping heads is:
(flips == "Heads").mean() # comparison operator gives you a list of boolean values, mean gives you the avg of 
                            # what you put in to compare

0.499972

In [4]:
# Another example: What is the probability of rolling a 5 on a 6 sided die?

# Step 1, represent our data's outcomes
outcomes = [1, 2, 3, 4, 5, 6]

# Step 2, create the data
n_simulations = 10_000

rolls = np.random.choice(outcomes, size=n_simulations)

# What are the chances we roll a 5?
(rolls == 5).mean()

0.167

In [5]:
(rolls)[0:10]

array([6, 2, 5, 3, 2, 6, 3, 3, 3, 2])

In [6]:
(rolls == 5)[0:10]

array([False, False,  True, False, False, False, False, False, False,
       False])

In [7]:
# what's the probability of rolling a 5?
# sum up the count of times the roll was 5
# divide by the total number of rolls
number_of_fives_rolled = (rolls == 5).sum()
total_number_of_rolls = len(rolls)
number_of_fives_rolled / total_number_of_rolls

0.167

In [8]:
(rolls == 5).mean()

0.167

In [9]:
# What is the probability we'll roll a 5 or a 6 on a 6 sided die?
(rolls >= 5).mean()

0.3312

In [10]:
# What is the probabiliyt of rolling less than a 3 (but not including 3)
(rolls < 3).mean()

0.3373

In [11]:
# What are the chances we roll something other than 3
(rolls != 3).mean()

0.835

## Let's Roll 2 Dice at Once!

1. Figure out a way to represent the data
2. Create a matrix of random data, rows=simulations, columns=trials
3. Apply an aggregagte row-wise to get the result of each simulation
4. Apply a final aggregate (probably the .mean) to get our probability

In [12]:
# What are the odds of rolling Snake Eyes on two dice?

# Step 1 Represent our outcomes
outcomes = [1, 2, 3, 4, 5, 6]

# Step 2: Create a matrix of random data where rows=simulations, columns=trial

# Simulation = the number of times we run the experiment
# Trials = the number of things in each experiment
n_simulations = 1_000_000
n_trials = 2 # b/c we're rolling 2 dice with each experiment

# size argument can set our simulation and trial size
rolls = np.random.choice(outcomes, size=(n_simulations, n_trials))
rolls.shape

(1000000, 2)

In [13]:
rolls[0:5]

array([[3, 5],
       [3, 3],
       [1, 5],
       [6, 2],
       [5, 6]])

In [14]:
# Step 3: Apply an aggregate row-wise
# axis=1 means sum across the rows
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls[0:5]

array([ 8,  6,  6,  8, 11])

In [15]:
# Axis=0 means sum up the entire column. 
# If you don't put an axis, the default is 0
# rolls.sum(axis=0)

In [16]:
# Step 4.
# Add up all the times that an experiment produces the sum of 2
(sum_of_rolls == 2).mean()

0.027799

In [17]:
theoretical = 1/6 * 1/6
print(f"Our theoretical probability of rolling snake eyes is 1/6 * 1/6, which is {theoretical}")

Our theoretical probability of rolling snake eyes is 1/6 * 1/6, which is 0.027777777777777776


In [18]:
# What is the probability of rolling a 7 on two dice
# 1+6, 2+5, 3+4, 4+3, 5+2, 6+1

# step 1: represent our outcomes
outcomes = [1, 2, 3, 4, 5, 6]

# Step 2: generate a matrix of random outcomes, simulations = rows, trials = columns
# size=(simulations, trials)
# size=(experiements, number_of_dice per experiment)
rolls = np.random.choice(outcomes, size=(10_000, 2))
rolls[0:4]

array([[3, 1],
       [1, 4],
       [6, 2],
       [5, 4]])

In [19]:
# Step 3, apply a row-wise aggregate
# axis=1 to apply sum to rows
sum_of_rolls = rolls.sum(axis=1)
sum_of_rolls[0:4]

array([4, 5, 8, 9])

In [20]:
p = (sum_of_rolls == 7).mean()
print(f"The experimental probability of rolling a sum of 7 on two dice at once is {p}")

The experimental probability of rolling a sum of 7 on two dice at once is 0.1697


In [21]:
# What's the probability of rolling 2 pips on 2 dice
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000

die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

# Each array here shares an index where index = simulation_number
die1[0:3], die2[0:3]

(array([2, 5, 2]), array([1, 6, 4]))

In [22]:
(die1 == 2)[0:10]

array([ True, False,  True, False, False,  True,  True, False, False,
       False])

In [23]:
(die2 == 2)[0:10]

array([False, False, False, False, False, False, False,  True, False,
       False])

In [24]:
# ((die1 == 2) & (die2 == 2))[0:10]
d1_rolled_2 = die1 == 2
d2_rolled_2 = die2 == 2

# d1_rolled_2[0:5], d2_rolled_2[0:5]
both_rolled_2 = d1_rolled_2 & d2_rolled_2
both_rolled_2[0:10]

array([False, False, False, False, False, False, False, False, False,
       False])

In [42]:
both_rolled_2.mean()

0.0298

In [25]:
1/6 * 1/6 # theorectical probability of rolling a 2 on one die is 1/6 and on a second die rolling a 2 is 1/6

0.027777777777777776

In [26]:
# What are the experimental probabilities of rolling each possible sum
df = pd.DataFrame()

# possible sum outcomes from 2 dice
df["outcome"] = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# write a lil' function that gets the probability
def get_prob(n): # takes in one number
    return (sum_of_rolls == n).mean()

get_prob(2)

0.0279

In [27]:
# set the probability to its own column
df["probability"] = df.outcome.apply(get_prob)

print("Sum outcome of rolling 2 dice and the probability of seeing that outcome")
df

Sum outcome of rolling 2 dice and the probability of seeing that outcome


outcome  probability
0         2       0.0279
1         3       0.0555
2         4       0.0820
3         5       0.1093
4         6       0.1378
5         7       0.1697
6         8       0.1410
7         9       0.1147
8        10       0.0811
9        11       0.0515
10       12       0.0295

## Setting our own probabilities

In [28]:
# Let's answer questions experimentally rather than theoretically
# What's the probability of flipping "Heads" on an unfair coin? Heads 55% Tails 45%

# Let's flip a coin 100,000 times and figure out the probability of flipping "Heads"

# Let's find a way to represent out data
outcomes = ["Heads", "Tails"]

flips = np.random.choice(outcomes, size=(10_000, 1), p=[0.55, 0.45]) # the 1 is 1 coin flip at a time. P is
                                                                    # probibility of heads 55% Tails 45%

(flips == "Heads").mean()

0.5431

In [45]:
# what are the chances of flipping two heads in a row?
flips = np.random.choice(outcomes, size=(10_000, 2), p=[0.55, 0.45])
flips[0:5]

array([[1, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 0]])

In [30]:
# It'll be a bit easier to check for two heads if the head = 1 and tail is 0
# might as well turn a binary into a binary

# let's say Heads is 1 and Tails is 0
outcomes = [1, 0]# changed it from "Heads, Tails" which gave boolean values to be 1, 0 to work better in suming
flips = np.random.choice(outcomes, size=(100_000, 2), p=[0.55, 0.45])
flips[0:4]

array([[0, 1],
       [1, 1],
       [1, 1],
       [0, 1]])

In [31]:
# axis=1 to sum across the rows, so we have as many sums as we had pairs of coin flips
num_of_heads = flips.sum(axis=1)
num_of_heads

array([1, 2, 2, ..., 1, 0, 0])

In [32]:
(num_of_heads == 2).mean()

0.30046

In [33]:
# theoretical probability of flipping 2 unfair coin heads in a row
0.55 * .55

0.30250000000000005

In [34]:
# What if this is a fair coin?
outcomes = [1, 0]
flips = np.random.choice(outcomes, size=(100_000, 2))
num_of_heads = flips.sum(axis=1)
(num_of_heads == 2).mean()

0.24874

In [35]:
# theoretical probability of flipping two heads in a row
.5 * .5

0.25

In [36]:
# Rolling two dice at a time, what is the probability of rolling an odd and then and even?

# Step 1 is represent the world in Pandas/Numpy 
first_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)
second_die = np.random.choice([1, 2, 3, 4, 5, 6], size=100_000)

first_die, second_die

(array([3, 3, 2, ..., 5, 3, 4]), array([2, 6, 6, ..., 5, 1, 5]))

In [46]:
# We need to represent the results of the first die as an array of booleans
first_die_is_odd = (first_die % 2 != 0)

In [38]:
second_die_is_even = (second_die % 2 == 0)

In [39]:
first_odd_second_even = (first_die_is_odd & second_die_is_even)
first_odd_second_even

array([ True,  True, False, ..., False, False, False])

In [40]:
first_odd_second_even.mean()

0.24996

In [41]:
# Theoretical probability
.5 * .5

0.25