In [1]:
import pandas as pd
import numpy as np

In [7]:
# 1. How likely is it that you roll doubles when rolling two dice?

outcomes = [1, 2, 3, 4, 5, 6] # represent our outcomes
n_simulations = 1_000_000 # create matrix of random data where rows = simulations , columns = trials

die1 = np.random.choice(outcomes, size=n_simulations) #size arugument can set our simulation and trial size
die2 = np.random.choice(outcomes, size=n_simulations)
sum_of_rolls = rolls.sum(axis=1)

(die1 == die2).mean()


0.167336

In [11]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting 
# more than 3 heads
heads = ["Heads", "Tails"]
n_simulations = 10_000
n_trials = 8

flips = np.random.choice(heads, size=(n_simulations, n_trials))
flips[0]



array(['Tails', 'Heads', 'Tails', 'Tails', 'Heads', 'Tails', 'Heads',
       'Heads'], dtype='<U5')

In [14]:
flips[0] == "Heads"

array([False,  True, False, False,  True, False,  True,  True])

In [20]:
#(flips[0] == "Heads")
#(flips[0] == "Heads").sum()

4

In [25]:
is_heads = flips == "Heads"
number_of_heads = is_heads.sum(axis=1)
number_of_heads

array([4, 5, 5, ..., 4, 2, 6])

In [26]:
number_of_heads == 3

array([False, False, False, ..., False, False, False])

In [28]:
(number_of_heads == 3).mean()

0.2171

In [30]:
x = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
])

In [33]:
x.sum()

18

In [34]:
x.sum(axis=0)

array([6, 6, 6])

In [35]:
x.sum(axis=1)

array([3, 6, 9])

In [36]:
(number_of_heads > 3).mean()

0.6368

In [41]:
#When we flip 10 coins at once, what’s the likelihood of flipping all headsheads = ["Heads", "Tails"]
heads = ["Heads", "Tails"]
n_simulations = 10_000
n_trials = 10

flips = np.random.choice(heads, size=(n_simulations, n_trials))
is_heads = flips == "Heads"
number_of_heads = is_heads.sum(axis=1)
number_of_heads


array([4, 6, 6, ..., 7, 7, 4])

In [42]:
(number_of_heads == 10).mean()

0.0005

In [48]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming 
#that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive 
#past both have data science students on them?
outcomes = ["web", "data"]
n_simulations = 1000
n_trials = 2
size = (n_simulations, n_trials)
cohorts = np.random.choice(outcomes, size=size, p=[0.75, 0.25])
cohorts



array([['data', 'web'],
       ['web', 'web'],
       ['web', 'web'],
       ...,
       ['web', 'web'],
       ['web', 'web'],
       ['web', 'web']], dtype='<U4')

In [50]:
is_ds = cohorts == "data"
number_of_ds = is_ds.sum(axis=1)
number_of_ds

array([1, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 2, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0,
       1, 2, 0, 0, 2, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 2, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 2, 1,
       0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 2, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 0, 0, 1, 1, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 2, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,

In [51]:
(number_of_ds == 2).mean()

0.067

In [52]:
.25 * .25

0.0625

In [ ]:
# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack 
# vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be 
# able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use 
# the np.random.normal)


In [ ]:
# 5. Compare Heights
    # Men have an average height of 178 cm and standard deviation of 8cm.
    # Women have a mean of 170, sd = 6cm.
    # Since you have means and standard deviations, you can use np.random.normal to generate observations.
    # If a man and woman are chosen at random, P(woman taller than man)?



In [ ]:
# 6a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
# and the installation fails. What are the odds that after having 50 students download anaconda, no one has an 
# installation issue? 100 students?



In [ ]:
# 6b. What is the probability that we observe an installation issue within the first 150 students that download 
# anaconda?



In [ ]:
# 6c. How likely is it that 450 students all download anaconda without an issue?


In [ ]:
# 7a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, 
# you haven't seen a food truck there in 3 days. How unlikely is this?

In [ ]:
# 7b. How likely is it that a food truck will show up sometime this week?

In [ ]:
#8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?