In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import viz
np.random.seed(29)

In [3]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4, 5],
       [6, 3, 1],
       [1, 2, 2],
       ...,
       [6, 2, 1],
       [3, 4, 3],
       [4, 2, 4]])

In [4]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([15, 10,  5, ...,  9, 10, 10])

NameError: name 'plt' is not defined

In [5]:
wins = sums_by_trial > 12
wins

array([ True, False, False, ..., False, False, False])

In [6]:
win_rate = wins.astype(int).mean()
win_rate

0.2633

In [8]:
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.0505000000000004

In [10]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.5860000000000003

In [11]:
p_nap = .3
ndays = ncols = 2
n_simulated_weekends = nrows = 10**5

In [12]:
data = np.random.random((nrows, ncols))
data

array([[0.46762045, 0.70078355],
       [0.18897809, 0.54312897],
       [0.253291  , 0.43836437],
       ...,
       [0.15008559, 0.37577491],
       [0.34690321, 0.58934311],
       [0.97135998, 0.57219933]])