In [2]:
import pandas as pd
import numpy as np
import random

In [14]:
# 1. How likely is it that you roll doubles when rolling two dice?
nrows = 100_000
ncols = 2
rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)
df = pd.DataFrame(rolls)
df['doubles'] = df[0] == df[1]
odds_of_doubles = int(round(df.doubles.mean(),2) * 100)

print(f'The odds of rolling doubles when rolling two dice are {odds_of_doubles}%')

#n_simulations = 1_000_000 # create matrix of random data where rows = simulations , columns = trials

#die1 = np.random.choice(outcomes, size=n_simulations) #size arugument can set our simulation and trial size
#die2 = np.random.choice(outcomes, size=n_simulations)
#sum_of_rolls = .sum(axis=1)

#(die1 == die2).mean()


The odds of rolling doubles when rolling two dice are 17%


In [34]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting 
# more than 3 heads

nrows = 100_000 # set rows to number of simulations
ncols = 8       # set columns to number of random events in each simulation

# create array
rolls = np.random.choice([True, False], nrows * ncols).reshape(nrows, ncols)

# create dataframe
df = pd.DataFrame(rolls)

# add calculation columnns
df['number_of_heads'] = df.sum(axis=1)
df['exactly_three_heads'] = df.number_of_heads == 3
df['three_or_more_heads'] = df.number_of_heads >= 3

# get mean of calculation True/False columns
# format and print results
odds_of_three_heads = int(round(df.exactly_three_heads.mean(),2) * 100)
odds_of_three_or_more_heads = int(round(df.three_or_more_heads.mean(),2) * 100)

print(f'The odds of getting exactly three heads when flipping eight coins is {odds_of_three_heads}%')
print(f'The odds of gettng three or more heads when flipping eight coins is {odds_of_three_or_more_heads}%')

The odds of getting exactly three heads when flipping eight coins is 22%
The odds of gettng three or more heads when flipping eight coins is 86%


In [15]:
# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting 
# more than 3 heads
heads = ["Heads", "Tails"]
n_simulations = 10_000
n_trials = 8

flips = np.random.choice(heads, size=(n_simulations, n_trials))
flips[0]



array(['Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Tails', 'Heads',
       'Tails'], dtype='<U5')

In [16]:
flips[0] == "Heads"

array([False, False, False, False, False, False,  True, False])

In [ ]:
#(flips[0] == "Heads")
#(flips[0] == "Heads").sum()

In [17]:
is_heads = flips == "Heads"
number_of_heads = is_heads.sum(axis=1)
number_of_heads

array([1, 3, 4, ..., 3, 5, 4])

In [18]:
number_of_heads == 3

array([False,  True, False, ...,  True, False, False])

In [19]:
(number_of_heads == 3).mean()

0.2157

In [20]:
x = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3]
])

In [21]:
x.sum()

18

In [23]:
x.sum(axis=0)

array([6, 6, 6])

In [24]:
x.sum(axis=1)

array([3, 6, 9])

In [25]:
(number_of_heads > 3).mean()

0.6393

In [26]:
#When we flip 10 coins at once, what’s the likelihood of flipping all headsheads = ["Heads", "Tails"]
heads = ["Heads", "Tails"]
n_simulations = 10_000
n_trials = 10

flips = np.random.choice(heads, size=(n_simulations, n_trials))
is_heads = flips == "Heads"
number_of_heads = is_heads.sum(axis=1)
number_of_heads


array([6, 3, 5, ..., 7, 5, 5])

In [27]:
(number_of_heads == 10).mean()

0.0009

In [28]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming 
#that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive 
#past both have data science students on them?
outcomes = ["web", "data"]
n_simulations = 1000
n_trials = 2
size = (n_simulations, n_trials)
cohorts = np.random.choice(outcomes, size=size, p=[0.75, 0.25])
cohorts



array([['data', 'web'],
       ['data', 'web'],
       ['web', 'web'],
       ...,
       ['data', 'web'],
       ['web', 'web'],
       ['web', 'web']], dtype='<U4')

In [36]:
# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming 
#that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive 
#past both have data science students on them?

nrows = 100_000 # set rows to number of simulations
ncols = 2       # set columns to number of bilboards in each simulation

# create data frame with each row representing a simulation and each column representing a bilboard in the simulation
rolls = np.random.choice(["DS","WEB","WEB","WEB"], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnn
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")

# get mean of calculation True/False columns
# format and print results
both_ds = int(round(df.both_ds.mean(),2) * 100)

print(f'The odds of both billboards being Data Science are {both_ds}%')

The odds of both billboards being Data Science are 6%


In [35]:
is_ds = cohorts == "data"
number_of_ds = is_ds.sum(axis=1)
number_of_ds.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [30]:
(number_of_ds == 2).mean()

0.065

In [31]:
.25 * .25

0.0625

In [37]:
# 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack 
# vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be 
# able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use 
# the np.random.normal)

nrows = 100_000 # set rows to number of simulations
ncols = 5       # set columns to number of days in each simulation

# create array with each row representing a simulation and each column representing a day in the simulation
rolls = np.random.normal(3, 1.5, nrows * ncols).astype(int).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(rolls)

# add calculation columnns
df['total_pop_tarts'] = df.sum(axis=1)
df['pop_tarts_remain'] = df['total_pop_tarts'] < 17

# get mean of calculation True/False columns
# format and print results
tarts = int(round(df['pop_tarts_remain'].mean(),2) * 100)

print(f'The odds of being able to by a PopTart in the afternoon on friday are {tarts}%')

The odds of being able to by a PopTart in the afternoon on friday are 88%


In [38]:
# 5. Compare Heights
    # Men have an average height of 178 cm and standard deviation of 8cm.
    # Women have a mean of 170, sd = 6cm.
    # Since you have means and standard deviations, you can use np.random.normal to generate observations.
    # If a man and woman are chosen at random, P(woman taller than man)?

# create arrays of veriables
male_hights = np.random.normal(178, 8, 100_000)
female_hights = np.random.normal(170, 6, 100_000)

# convert array to data frame
df = pd.DataFrame({"male_hights" : male_hights,
                   "female_hights" : female_hights})

# add calculated column
df['female_is_taller'] = df.female_hights > df.male_hights

# get mean of female_is_taller
df['female_is_taller'].mean()

# get mean of calculation True/False columns
# format and print results
taller_female = int(round(df['female_is_taller'].mean(),2) * 100)

print(f"The probability of a woman, chosen at random, being taller than a man, chosen at random is {taller_female}%")


The probability of a woman, chosen at random, being taller than a man, chosen at random is 21%


In [39]:
# 6a. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
# and the installation fails. What are the odds that after having 50 students download anaconda, no one has an 
# installation issue? 100 students?

nrows = 100_000 # set rows to number of simulations
ncols = 50      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 50 students dowloading Anaconda without a problem are {problems}%')


The odds of 50 students dowloading Anaconda without a problem are 82%


In [40]:
# 6b. 100 students?

nrows = 100_000 # set rows to number of simulations
ncols = 100     # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 100 students dowloading Anaconda without a problem are {problems}%')

The odds of 100 students dowloading Anaconda without a problem are 67%


In [41]:
# 6b. What is the probability that we observe an installation issue within the first 150 students that download 
# anaconda?

nrows = 100_000 # set rows to number of simulations
ncols = 150      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_a_problem'] = df.sum(axis=1) > 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_a_problem'].mean(),2) * 100)

print(f'The odds of a problem occuring in the first 150 instllations is {problems}%')

The odds of a problem occuring in the first 150 instllations is 45%


In [43]:
# 6c. How likely is it that 450 students all download anaconda without an issue?

nrows = 100_000 # set rows to number of simulations
ncols = 450      # set columns to number of students in each simulation

# list with 249 falses and one true
issue_range = [False for r in range(1,250)]
issue_range.append(True)

# create array with each row representing a simulation and each column representing a student in the simulation
installs = np.random.choice(issue_range, nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(installs)

# add calculation columnns
df['has_no_problem'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
problems = int(round(df['has_no_problem'].mean(),2) * 100)

print(f'The odds of 450 instllations occuring without an issue is {problems}%')

The odds of 450 instllations occuring without an issue is 16%


In [49]:
# 7a. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, 
# you haven't seen a food truck there in 3 days. How unlikely is this?

nrows = 100_000 # set rows to number of simulations
ncols = 3      # set columns to number of days in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['times_sighted'] = df.sum(axis=1)
df['not_sighted_three_days'] = df.times_sighted == 0

df['not_sighted_three_days'].mean()

# get mean of calculation True/False columns
# format and print results
trucks = int(round(df['not_sighted_three_days'].mean(),2) * 100)

print(f'The odds of not seeing a food truck in Travis Park for three days is {trucks}%')


The odds of not seeing a food truck in Travis Park for three days is 3%


In [46]:
# 7b. How likely is it that a food truck will show up sometime this week?

# Remaining week days
nrows = 100_000 # set rows to number of simulations
ncols = 2      # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([True, False], nrows * ncols, p=[.7,.3]).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['not_sighted_two_days'] = df.sum(axis=1) == 0

# get mean of calculation True/False columns
# format and print results
trucks = int(round(df['not_sighted_two_days'].mean(),4) * 100)

print(f'The odds of not seeing a food truck in Travis Park for {ncols} days is {trucks}%')

The odds of not seeing a food truck in Travis Park for 2 days is 8%


In [54]:
#8. If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?

nrows = 100_000 # set rows to number of simulations
ncols = 23       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly least two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 23 people having exactly least two people that share a birthday are 13%


In [55]:
# 8b. What if it's 20 people? 40?

nrows = 100_000 # set rows to number of simulations
ncols = 20       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly least two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 20 people having exactly least two people that share a birthday are 9%


In [56]:
# 8c. What if it is 40?
nrows = 100_000 # set rows to number of simulations
ncols = 40       # set columns to number of students in each simulation

# create array with each row representing a simulation and each column representing a student in the simulation
sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

# convert to data frame
df = pd.DataFrame(sightings)

# add calculation columnns
df['at_least_two_matching_birthdays'] = df.nunique(axis=1) < ncols
df['exactly_two_matching_birthdays'] = df.nunique(axis=1) == ncols-1

# get mean of calculation True/False columns
# format and print results
at_least_two_matching_birthdays = int(round(df['at_least_two_matching_birthdays'].mean(),2) * 100)
exactly_two_matching_birthdays = int(round(df['exactly_two_matching_birthdays'].mean(),2) * 100)

print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {at_least_two_matching_birthdays}%')
print(f'The odds of a room of {ncols} people having exactly two people that share a birthday are {exactly_two_matching_birthdays}%')

The odds of a room of 40 people having at least two people that share a birthday are 89%
The odds of a room of 40 people having exactly two people that share a birthday are 28%
